Repository w3c/csswg-drafts, pull requests merged in 2018-04, with the labels that each got.

#2525 [css-transforms] 2D and 3D rotation are distinct
  css-transforms-2/Overview.bs
Labels: ready

#2522 [css-transforms-1] Focus definition of neutral element to the needs o…
  css-transforms-1/Overview.bs
Labels: ready

#2534 [cssom] Fix #2403 and #2149
  cssom-1/Overview.bs
Labels: ready

#2599 Display contents svg
  css-display-3/Overview.bs
Labels: ready

#2596 Deal with overflow:clip
  css-align-3/Overview.bs
  css-flexbox-1/Overview.bs
  css-grid-1/Overview.bs
  css-transforms-2/Overview.bs
  cssom-view-1/Overview.bs
Labels: Needs Feedback/Review, css-align-3, css-flexbox-1, css-grid-1, css-transforms-2, cssom-view-1

#2563 Fix #1548.
  cssom-1/Overview.bs
Labels: cssom-1

#2603 Mention "CSS namespace" rather than "CSS interface"
  css-conditional-3/Overview.bs
Labels: ready

#2620 [css-grid-2] Updating initial example to match per-axis model
  css-grid-2/Overview.bs
Labels: ready

#1986 [css-syntax] Trim whitespace from the beginning/ending of a declarati…
  css-syntax-3/Overview.bs
Labels: Needs Testcase (WPT), css-syntax-3
